# Generated by Django 5.0.7 on 2024-07-29 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Category')),
                ('description', models.TextField(help_text='Опишите продукт', max_length=250, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=150, verbose_name='Product')),
                ('description', models.TextField(help_text='Опишите продукт', max_length=250, verbose_name='Description')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='product/preview_img/', verbose_name='PreviewImg')),
                ('price_purchase', models.FloatField(help_text='Цена продукта', verbose_name='PricePurchase')),
                ('created_at', models.DateField(help_text='Дата создания')),
                ('updated_at', models.DateField(help_text='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name', 'category', 'price_purchase', 'created_at', 'updated_at'),
            },
        ),
    ]
