# Generated by Django 5.0.7 on 2024-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(blank=True, help_text='Дата производства', null=True, verbose_name='Дата производства продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Дата создания', verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(auto_now=True, help_text='Дата обновления', null=True, verbose_name='updated_at'),
        ),
    ]
